# Generated by Dashboard Layout Architect
# Copy-paste into a new app.R file and run

library(shiny)
library(bslib)
library(bsicons)

# ── Theme ──────────────────────────────────────────────────────────
theme <- bs_theme(
  bg      = '#F8F9FA',
  fg      = '#1F2937',
  primary = '#0097A7'
) |> bs_add_variables(
  'card-bg'      = '#FFFFFF',
  'border-color' = '#E5E7EB',
  'border-radius' = '8px'
)

# ── UI ─────────────────────────────────────────────────────────────
ui <- page_sidebar(
  title = div(
    img(src = 'logo.png', height = '40px', alt = 'Logo',
        style = 'margin-right:12px; display:inline-block;'),
    'My Dashboard'
  ),
  theme = theme,
  sidebar = sidebar(
    width = 260,
    h4('Navigation'),
    nav_item(actionLink('nav_1', 'Menu Item 1')),
    nav_item(actionLink('nav_2', 'Menu Item 2')),
    nav_item(actionLink('nav_3', 'Menu Item 3')),
    nav_item(actionLink('nav_4', 'Menu Item 4')),
    nav_item(actionLink('nav_5', 'Menu Item 5')),
  ),

  # KPI Row
  layout_columns(
    fill = FALSE,
    col_widths = c(3, 3, 3, 3),
    value_box(title = 'KPI 1', value = '...', showcase = bsicons::bs_icon('graph-up')),
    value_box(title = 'KPI 2', value = '...', showcase = bsicons::bs_icon('graph-up')),
    value_box(title = 'KPI 3', value = '...', showcase = bsicons::bs_icon('graph-up')),
    value_box(title = 'KPI 4', value = '...', showcase = bsicons::bs_icon('graph-up'))
  ),

  # Main Grid (Uniform)
  layout_columns(
    col_widths = c(6, 6),
    fill = TRUE,
    card(card_header('Chart 1'), card_body(plotOutput('plot_1'))),
    card(card_header('Chart 2'), card_body(plotOutput('plot_2'))),
    card(card_header('Chart 3'), card_body(plotOutput('plot_3'))),
    card(card_header('Chart 4'), card_body(plotOutput('plot_4')))
  )
)

# ── Server ─────────────────────────────────────────────────
server <- function(input, output, session) {
  output$plot_1 <- renderPlot({ plot(cars, main = 'Chart 1') })
  output$plot_2 <- renderPlot({ plot(cars, main = 'Chart 2') })
  output$plot_3 <- renderPlot({ plot(cars, main = 'Chart 3') })
  output$plot_4 <- renderPlot({ plot(cars, main = 'Chart 4') })
}

shinyApp(ui, server)